-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON H.CAR_ID=C.CAR_ID
WHERE C.CAR_TYPE LIKE '세단' AND DATE_FORMAT(H.START_DATE,'%m') = 10
GROUP BY CAR_ID
ORDER BY CAR_ID DESC